**Name:** Timothy Mayabi

**Email**: usafiri2018@gmail.com

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

# Data Overview

In [6]:
# Load the customer churn dataset
file_path = "../data/customer_churn.xlsx"
df = pd.read_excel(
    file_path,
    sheet_name='Data for DSBA'
)

#Inspect the dataset
print("Dataset shape:", df.shape)

display(df.head())
df.info()

Dataset shape: (11260, 19)

,AccountID,Churn,Tenure,City_Tier,CC_Contacted_LY,Payment,Gender,Service_Score,Account_user_count,account_segment,CC_Agent_Score,Marital_Status,rev_per_month,Complain_ly,rev_growth_yoy,coupon_used_for_payment,Day_Since_CC_connect,cashback,Login_device
0,20000,1,4,3.0,6.0,Debit Card,Female,3.0,3,Super,2.0,Single,9,1.0,11,1,5,159.93,Mobile
1,20001,1,0,1.0,8.0,UPI,Male,3.0,4,Regular Plus,3.0,Single,7,1.0,15,0,0,120.9,Mobile
2,20002,1,0,1.0,30.0,Debit Card,Male,2.0,4,Regular Plus,3.0,Single,6,1.0,14,0,3,NaN,Mobile
3,20003,1,0,3.0,15.0,Debit Card,Male,2.0,4,Super,5.0,Single,8,0.0,23,0,3,134.07,Mobile
4,20004,1,0,1.0,12.0,Credit Card,Male,2.0,3,Regular Plus,5.0,Single,3,0.0,11,1,3,129.6,Mobile

<class 'pandas.DataFrame'>
RangeIndex: 11260 entries, 0 to 11259
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   AccountID                11260 non-null  int64
 1   Churn                    11260 non-null  int64
 2   Tenure                   11158 non-null  object
 3   City_Tier                11148 non-null  float64
 4   CC_Contacted_LY          11158 non-null  float64
 5   Payment                  11151 non-null  str
 6   Gender                   11152 non-null  str
 7   Service_Score            11162 non-null  float64
 8   Account_user_count       11148 non-null  object
 9   account_segment          11163 non-null  str
 10  CC_Agent_Score           11144 non-null  float64
 11  Marital_Status           11048 non-null  str
 12  rev_per_month            11158 non-null  object
 13  Complain_ly              10903 non-null  float64
 14  rev_growth_yoy           11260 non-null  object
 15  coupon_used_for_payment  11260 non-null  object
 16  Day_Since_CC_connect     10903 non-null  object
 17  cashback                 10789 non-null  object
 18  Login_device             11039 non-null  str
dtypes: float64(5), int64(2), object(7), str(5)
memory usage: 1.6+ MB

## Descriptive Statistics

This section examines the distribution and summary statistics of numerical and categorical variables to understand the characteristics of customer accounts

In [7]:
# Numerical variables
display(df.describe())

# Categorical variables
display(df.describe(include=['object', 'str']))

,AccountID,Churn,City_Tier,CC_Contacted_LY,Service_Score,CC_Agent_Score,Complain_ly
count,11260.00000,11260.000000,11148.000000,11158.000000,11162.000000,11144.000000,10903.000000
mean,25629.50000,0.168384,1.653929,17.867091,2.902526,3.066493,0.285334
std,3250.62635,0.374223,0.915015,8.853269,0.725584,1.379772,0.451594
min,20000.00000,0.000000,1.000000,4.000000,0.000000,1.000000,0.000000
25%,22814.75000,0.000000,1.000000,11.000000,2.000000,2.000000,0.000000
50%,25629.50000,0.000000,1.000000,16.000000,3.000000,3.000000,0.000000
75%,28444.25000,0.000000,3.000000,23.000000,3.000000,4.000000,1.000000
max,31259.00000,1.000000,3.000000,132.000000,5.000000,5.000000,1.000000

,Tenure,Payment,Gender,Account_user_count,account_segment,Marital_Status,rev_per_month,rev_growth_yoy,coupon_used_for_payment,Day_Since_CC_connect,cashback,Login_device
count,11158,11151,11152,11148,11163,11048,11158,11260,11260,10903,10789.00,11039
unique,38,5,4,7,7,3,59,20,20,24,5693.00,3
top,1,Debit Card,Male,4,Super,Married,3,14,1,3,155.62,Mobile
freq,1351,4587,6328,4569,4062,5860,1746,1524,4373,1816,10.00,7482

## Investigate incorrectly classified variables

In this section, we identify the values preventing expected numerical columns from being interpreted correctly.

In [8]:
# Columns expected to contain numerical values
numeric_columns = [
    "Tenure",
    "Account_user_count",
    "rev_per_month",
    "rev_growth_yoy",
    "coupon_used_for_payment",
    "Day_Since_CC_connect",
    "cashback"
]

for col in numeric_columns:
    converted = pd.to_numeric(df[col], errors='coerce')

    invalid_values = df.loc[
        df[col].notna() & converted.isna(), col
    ].unique()

    print(f"\n{col}")
    print("Current dtype:", df[col].dtype)
    print("Invalid values:", invalid_values)

Tenure
Current dtype: object
Invalid values: ['#']

Account_user_count
Current dtype: object
Invalid values: ['@']

rev_per_month
Current dtype: object
Invalid values: ['+']

rev_growth_yoy
Current dtype: object
Invalid values: ['$']

coupon_used_for_payment
Current dtype: object
Invalid values: ['#' '$' '*']

Day_Since_CC_connect
Current dtype: object
Invalid values: ['$']

cashback
Current dtype: object
Invalid values: ['$']

## Missing value analysis

This will show us which variables have missing values and the proportion of affected records

In [9]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing Count"] > 0
].sort_values(
    by="Missing Percentage",
    ascending=False
)
display(missing_summary)

                      Missing Count  Missing Percentage
cashback                        471                4.18
Complain_ly                     357                3.17
Day_Since_CC_connect            357                3.17
Login_device                    221                1.96
Marital_Status                  212                1.88
CC_Agent_Score                  116                1.03
City_Tier                       112                0.99
Account_user_count              112                0.99
Payment                         109                0.97
Gender                          108                0.96
Tenure                          102                0.91
CC_Contacted_LY                 102                0.91
rev_per_month                   102                0.91
Service_Score                    98                0.87
account_segment                  97                0.86

## Check duplicate records

In [10]:
print ("Duplicate rows: ", df.duplicated().sum())

print("Duplicated Account Ids:", df["AccountID"].duplicated().sum())

Duplicate rows:  0
Duplicated Account Ids: 0

### Initial Data Quality Observations

The dataset contains 11,260 customer account records and 19 variables, including the target variable `Churn`.

**Key observations:**

1. The overall churn rate is approximately 16.84%, indicating that churned accounts represent a minority of the dataset. This class imbalance will need to be considered during model development.
2. Customer care interactions vary considerably across accounts, with some recording up to 132 contacts in the previous year.
3. Average service satisfaction and customer care satisfaction scores are approximately 2.90 and 3.07, respectively.
4. Several numerical variables have been incorrectly classified as categorical because they contain special characters such as `#`, `@`, `$`, `+`, and `*`.
5. Missing values exist across multiple variables, with `cashback`, `Complain_ly`, and `Day_Since_CC_connect` having the highest initially observed missing percentages.
6. No duplicate records or account identifiers were identified.

**Conclusion:** The dataset requires additional cleaning, particularly numerical type conversion, missing-value treatment, and categorical consistency checks, before reliable exploratory analysis can be performed.

# Data Cleaning and Preprocessing

## Correct invalid numerical values and data types

In [12]:
# Create a working copy to preserve the original dataset

df_clean = df.copy()

# Numerical columns requiring correction

numeric_columns = [
    "Tenure",
    "Account_user_count",
    "rev_per_month",
    "rev_growth_yoy",
    "coupon_used_for_payment",
    "Day_Since_CC_connect",
    "cashback"
]

# Convert invalid values to NaN and correct data types
for col in numeric_columns:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')


# Verify corrected data types
print("Corrected numerical data types:")
print(df_clean[numeric_columns].dtypes)

# Missing values after numerical conversion
missing_after_conversion = pd.DataFrame({
    "Missing Count": df_clean.isnull().sum(),
    "Missing Percentage": (
        df_clean.isnull().sum() / len(df_clean) * 100
    ).round(2)
})

missing_after_conversion = (
    missing_after_conversion[missing_after_conversion["Missing Count"] > 0].sort_values(by="Missing Percentage", ascending=False)
)

display(missing_after_conversion)

Corrected numerical data types:
Tenure                     float64
Account_user_count         float64
rev_per_month              float64
rev_growth_yoy             float64
coupon_used_for_payment    float64
Day_Since_CC_connect       float64
cashback                   float64
dtype: object

                         Missing Count  Missing Percentage
rev_per_month                      791                7.02
cashback                           473                4.20
Account_user_count                 444                3.94
Day_Since_CC_connect               358                3.18
Complain_ly                        357                3.17
Login_device                       221                1.96
Tenure                             218                1.94
Marital_Status                     212                1.88
CC_Agent_Score                     116                1.03
City_Tier                          112                0.99
Payment                            109                0.97
Gender                             108                0.96
CC_Contacted_LY                    102                0.91
Service_Score                       98                0.87
account_segment                     97                0.86
rev_growth_yoy                       3                0.03
coupon_used_for_payment              3                0.03